name: pullrequest-master

on:
  pull_request:
    branches:
      - master

jobs:
  build-and-deply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup node env 🏗
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
          check-latest: true

      - name: Cache node_modules 📦
        uses: actions/cache@v2.1.4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies 👨🏻‍💻
        run: npm ci --prefer-offline --no-audit

      # Eslintチェック
      - name: Run linter 👀
        run: npm run lint

      - name: Build Project
        run: npm run generate

      - name: List output files
        working-directory: dist
        run: ls

      # テストサーバーへのデプロイ
      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env: # FTP環境設定
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          LOCAL_DIR: dist/
          REMOTE_DIR: www/event-dev/
          ARGS: --delete
