name: push-master

on:
  push:
    branches:
      - master

jobs:
  FTP-Deploy:
    name: FTP-Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@master

      - name: Setup node env v14.18
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "14"

      - name: Build Project
        run: |
          npm ci
          npm run generate

      - name: List output files
        run: ls

      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env: # FTP環境設定
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          LOCAL_DIR: /dist
          REMOTE_DIR: ${{ secrets.FTP_DIR_PRDUCTION }}
          ARGS: --delete
